export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const LOADING_PINS = 'LOADING_PINS';
export const LOADING_SWITCHES = 'LOADING_SWITCHES';
export const ADD_SWITCH = 'ADD_SWITCH';
export const ADD_SWITCHES = 'ADD_SWITCHES';
export const REMOVE_SWITCH= 'REMOVE_SWITCH';
export const ADD_PINS = 'ADD_PINS';
export const TOGGLE_SWITCH = 'TOGGLE_SWITCH';
