swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger Rest Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /switches:          
    get:
      operationId: applianceHandler.read_all
      tags:
        - appliances
      summary: Read the entire list of appliances
      description: Read the list of appliances
      responses:
        200:
          description: Successfully read swtiches list operation
          schema:
            type: array
            items:
              properties:
                state:
                  type: string
                pin:
                  type: string
                  
    post:
      operationId: applianceHandler.create
      tags:
        - appliances
      summary: Create a switch and add it to the appliances list
      description: Create a new switch in the appliances list
      parameters:
        - name: appliance
          in: body
          description: switch to create
          required: True
          schema:
            type: object
            properties:
              label:
                type: string
                description: label
              pin:
                type: integer
                description: pin output
      responses:
        201:
          description: Successfully created appliance in list

                  
  /switches/{id}:                  
    get:
      operationId: applianceHandler.read_one
      tags:
        - appliances
      summary: Read one switch from the switches list
      description: Read one switch from the switches list
      parameters:
        - name: id
          in: path
          description: id of the switch to get from the list
          type: string
          required: True
      responses:
        200:
          description: Successfully read switch from switches list operation
          schema:
            properties:
              state:
                type: string
              pin:
                type: integer
                
    delete:
      operationId: applianceHandler.delete
      tags:
        - appliances
      summary: Delete a switch from the appliances list
      description: Delete a switch
      parameters:
        - name: id
          in: path
          type: string
          required: True
      responses:
        200:
          description: Successfully deleted a switch from appliances list
          
    put:
      operationId: applianceHandler.update
      tags:
        - appliances
      summary: Update a appliance in the appliances list
      description: Update a appliance in the appliances list
      parameters:
        - name: id
          in: path
          description: id of the appliance to update in the list
          type: string
          required: True
        - name: appliance
          in: body
          schema:
            type: object
            properties:
              label:
                type: string
              pin:
                type: integer
      responses:
        200:
          description: Successfully updated switch in switches list          

  /switches/{id}/toggle:  
    put:
      operationId: applianceHandler.toggle
      tags:
        - appliances
      summary: Update a appliance in the switches list
      description: Update a appliance in the switches list
      parameters:
        - name: id
          in: path
          description: label of the appliance to update in the list
          type: string
          required: True
      responses:
        200:
          description: Successfully updated appliance in state
          
  /pins:     
    get:
      operationId: pins.read_all
      tags:
        - pins
      summary: Read the entire list of pins
      description: Read the list of pins
      parameters:
        - name: length
          in: query
          type: integer
          description: Number of pins to get from pins
          required: false
        - name: offset
          in: query
          type: integer
          description: Offset from beginning of list where to start gathering pins
          required: false
      responses:
        200:
          description: Successfully read pins list operation
          schema:
            type: array
            items:
              properties:
                name:
                  type: string
                pin:
                  type: integer
                    